services:
  database:
    image: postgres:18-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5

  migrate:
    image: app
    entrypoint: alembic upgrade head
    depends_on:
      database:
        condition: service_healthy
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql+psycopg://${POSTGRES_USER:?missing}:${POSTGRES_PASSWORD:?missing}@database:5432/${POSTGRES_DB:?missing}

  rabbitmq:
    image: rabbitmq:3-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/mnesia/
    healthcheck:
      test: ["CMD-SHELL", "rabbitmq-diagnostics -q ping"]
      interval: 10s
      timeout: 10s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
    - redis_data:/data

  app:
    image: app
    command: uvicorn app.main:app --host 0.0.0.0 --port "${PORT:-8000}" --log-level info
    build: .
    ports:
      - "8000:8000"
    depends_on:
      database:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql+psycopg://${POSTGRES_USER:?missing}:${POSTGRES_PASSWORD:?missing}@database:5432/${POSTGRES_DB:?missing}
      CELERY_BROKER_URL: ${CELERY_BROKER_URL}
      CELERY_RESULT_BACKEND: ${CELERY_RESULT_BACKEND}
    volumes:
      # Python
      - ./app:/app/app
      - ./tests:/app/tests

      # Scripts
      - ./entrypoint.sh:/app/entrypoint.sh

      # Migrations
      - ./alembic:/app/alembic
      - ./alembic.ini:/app/alembic.ini

  celery_worker:
    image: app
    command: celery -A app.tasks.celery_app.celery_app worker --loglevel=info
    depends_on:
      database:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql+psycopg://${POSTGRES_USER:?missing}:${POSTGRES_PASSWORD:?missing}@database:5432/${POSTGRES_DB:?missing}
      CELERY_BROKER_URL: ${CELERY_BROKER_URL}
      CELERY_RESULT_BACKEND: ${CELERY_RESULT_BACKEND}
    volumes:
      - ./app:/app/app
      - ./tests:/app/tests

  celery_beat:
    image: app
    command: celery -A app.tasks.celery_app.celery_app beat --loglevel=info --schedule /tmp/celerybeat-schedule
    depends_on:
      database:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql+psycopg://${POSTGRES_USER:?missing}:${POSTGRES_PASSWORD:?missing}@database:5432/${POSTGRES_DB:?missing}
      CELERY_BROKER_URL: ${CELERY_BROKER_URL}
      CELERY_RESULT_BACKEND: ${CELERY_RESULT_BACKEND}
    volumes:
      - ./app:/app/app
      - ./tests:/app/tests

  flower:
    image: app
    command: celery -A app.tasks.celery_app.celery_app flower --logging=info
    ports:
      - "5555:5555"
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql+psycopg://${POSTGRES_USER:?missing}:${POSTGRES_PASSWORD:?missing}@database:5432/${POSTGRES_DB:?missing}
      CELERY_BROKER_URL: ${CELERY_BROKER_URL}
      CELERY_RESULT_BACKEND: ${CELERY_RESULT_BACKEND}
      FLOWER_UNAUTHENTICATED_API: "true"

volumes:
  pgdata:
  redis_data:
  rabbitmq_data: